CREATE TABLE CRL_ISSUER (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(250) NOT NULL UNIQUE,
	description VARCHAR(200)
);

CREATE TABLE CRL_DOWNLOAD_ADDRESS (
	address VARCHAR(200) NOT NULL,
	issuer_id INT UNSIGNED NOT NULL,
	description VARCHAR(200)
);
ALTER TABLE CRL_DOWNLOAD_ADDRESS ADD FOREIGN KEY (issuer_id) REFERENCES CRL_ISSUER(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE CRL_DOWNLOAD_ADDRESS ADD PRIMARY KEY (issuer_id, address);

CREATE TABLE UPDATE_LOG (
	id CHAR(40) NOT NULL PRIMARY KEY,
	last_update_timestamp TIMESTAMP NOT NULL,
	update_status CHAR(1) NOT NULL,
	issuer_id INT UNSIGNED NOT NULL
);
ALTER TABLE UPDATE_LOG ADD FOREIGN KEY (issuer_id) REFERENCES CRL_ISSUER(id) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE CERT_REVOCATION_REASON (
	code INT UNSIGNED NOT NULL PRIMARY KEY,
	name VARCHAR(30) NOT NULL UNIQUE,
	description VARCHAR(100)
);

CREATE TABLE REVOKED_CERTIFICATE (
	serial_number BIGINT(19) NOT NULL,
	revocation_timestamp TIMESTAMP NOT NULL,
	revocation_code INT UNSIGNED,
	issuer_id INT UNSIGNED NOT NULL
);
ALTER TABLE REVOKED_CERTIFICATE ADD FOREIGN KEY (issuer_id) REFERENCES CRL_ISSUER(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE REVOKED_CERTIFICATE ADD PRIMARY KEY(issuer_id, serial_number);
ALTER TABLE REVOKED_CERTIFICATE ADD FOREIGN KEY (revocation_code) REFERENCES CERT_REVOCATION_REASON(code) ON UPDATE CASCADE ON DELETE SET NULL;

